gammaswap/v1-core

contracts/strategies/base/BaseStrategy.sol, contracts/test/strategies/base/TestBaseShortStrategy.sol, contracts/test/strategies/base/TestBaseStrategy.sol, contracts/test/strategies/base/TestBorrowStrategy.sol, contracts/test/strategies/base/TestLiquidationStrategy.sol, contracts/test/strategies/base/TestLongStrategy.sol, contracts/test/strategies/base/TestRebalanceStrategy.sol, contracts/test/strategies/base/TestRepayStrategy.sol, contracts/test/strategies/external/TestExternalBaseStrategy.sol, contracts/test/strategies/external/TestExternalLiquidationStrategy.sol, contracts/test/strategies/external/TestExternalRebalanceStrategy.sol, package.json
synchronize CFMM tracked token balances with actual token balances in CFMM
=> synchronize CFMM tracked token balances

contracts/strategies/base/BaseBorrowStrategy.sol, contracts/strategies/base/BaseLiquidationStrategy.sol, contracts/strategies/base/BaseLongStrategy.sol, contracts/strategies/base/BaseRepayStrategy.sol, contracts/strategies/base/BaseStrategy.sol, contracts/strategies/lending/BorrowStrategy.sol, contracts/strategies/lending/RepayStrategy.sol, contracts/strategies/liquidation/BatchLiquidationStrategy.sol, contracts/strategies/liquidation/ExternalLiquidationStrategy.sol, contracts/utils/Pausable.sol, package.json, test/strategies/external/ExternalLiquidationStrategy.test.ts
-Fixed rounding issue while liquidating in batch
-Added saftey rounding checks while subtracting numbers
-Made some gas efficiency gains using unchecked keyword
-Fix external liquidation bug
=> External Liquidation Bug Fix

contracts/strategies/base/BaseLiquidationStrategy.sol, contracts/strategies/base/BaseStrategy.sol, contracts/strategies/liquidation/ExternalLiquidationStrategy.sol, package.json, test/strategies/external/ExternalLiquidationStrategy.test.ts
-Liquidation external bug
-fix ema util rate calculation bug
-refund excess liquidity using minBorrow threshold only, update external liquidations hardhat tests
=> Liq external bug

contracts/strategies/base/BaseExternalStrategy.sol, contracts/test/strategies/external/TestExternalCallee2.sol, package.json, test/foundry/ExternalRebalanceStrategy.t.sol, test/strategies/external/ExternalBaseStrategy.test.ts
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205769995387360
=> fix lp calc function, add foundry test for rebalance strategy

hardhat.config.ts
-adding customChains field to etherscan part of hardhat config file
=> Etherscan custom chains

contracts/strategies/liquidation/SingleLiquidationStrategy.sol, package.json
remove minus minBorrow in SingleLiquidationStrategy
=> remove minus minBorrow in LiquidationStrategy

contracts/strategies/base/BaseLongStrategy.sol, contracts/strategies/lending/RepayStrategy.sol, contracts/strategies/liquidation/SingleLiquidationStrategy.sol, contracts/test/strategies/base/TestBorrowStrategy.sol, contracts/test/strategies/base/TestLiquidationStrategy.sol, contracts/test/strategies/base/TestLongStrategy.sol, contracts/test/strategies/base/TestRebalanceStrategy.sol, contracts/test/strategies/base/TestRepayStrategy.sol, contracts/test/strategies/external/TestExternalBaseStrategy.sol, contracts/test/strategies/external/TestExternalLiquidationStrategy.sol, contracts/test/strategies/external/TestExternalRebalanceStrategy.sol, package.json
-add maxAmounts vairable to calcTokensToRepay and use it in SingleLiquidationStrategy and RepayStrategy.
-update test conctracts with new changes
=> Cap calctokens2repay

contracts/base/GammaPool.sol, contracts/interfaces/IGammaPool.sol, contracts/interfaces/strategies/lending/IBorrowStrategy.sol, contracts/strategies/lending/BorrowStrategy.sol, contracts/test/strategies/TestBorrowStrategy2.sol, package.json
return tokensHeld (collateral) in borrowLiquidity (strategy/gammapool function) to check for slippage in PositionManager
=> Return Collateral in borrowLiquidity

contracts/GammaPoolFactory.sol, contracts/base/AbstractGammaPoolFactory.sol, contracts/interfaces/IGammaPool.sol, contracts/interfaces/IGammaPoolFactory.sol, contracts/interfaces/IProtocol.sol, package.json, test/GammaPoolFactory.test.ts
-added IProtocol interface to use in GammaPoolFactory in place of IGammaPool
-GammaPoolFactory calls execute() instead of setPoolParams() on pool contract
=> Protocol Interface

contracts/GammaPoolFactory.sol, contracts/base/AbstractGammaPoolFactory.sol, contracts/interfaces/IGammaPoolFactory.sol, contracts/libraries/AddressCalculator.sol, contracts/test/TestGammaPoolFactory.sol, contracts/test/TestGammaPoolFactory2.sol, contracts/utils/MinimalBeacon.sol, contracts/utils/MinimalBeaconProxy.sol, hardhat.config.ts, package.json
-minimal beacon implementation for etherscan to be able to verify minimal beacon proxy
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206311153753005
=> Minimal Beacon

contracts/base/GammaPool.sol, hardhat.config.ts, package.json, test/GammaPoolFactory.test.ts
-change update parameters in gammapool error codes to lower contract size
-add arbitrumSepolia configs to hardhat config file
=> change update parameters

contracts/base/PoolViewer.sol, package.json, test/GammaPool.test.ts
-pool viewer updated to handle cfmms with zero liquidity
=> Zero liquidity cfmm

contracts/strategies/base/BaseBorrowStrategy.sol, package.json
-apply minBorrow check when opening a position only when borrowing liquidity for a loan for the first time.
=> borrow more liquidity

contracts/strategies/base/BaseBorrowStrategy.sol, package.json
-check total borrowed liquidity against minBorrow
=> check total borrowed liquidity vs minBorrow

contracts/libraries/LibStorage.sol, contracts/rates/LogDerivativeRateModel.sol, contracts/strategies/base/BaseStrategy.sol, contracts/test/strategies/base/TestBorrowStrategy.sol, package.json, test/GammaPool.test.ts, test/GammaPoolFactory.test.ts, test/strategies/BaseStrategy.test.ts, test/strategies/LongStrategy.test.ts
-allow the cfmm fee index to leverage itself
-change interest rate calculation to take the max of the adjusted borrow rate or the cfmm fee index
-change parameters in origination fee model to lower the dynamic origination fees
-update unit tests
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206646768857400
=> Feat: zero spreads

contracts/strategies/base/BaseStrategy.sol, package.json
-cap the CFMM yield's leverage at 5x
-add function to add spread to cfmmFeeIndex
=> Feat: cap cfmm yield

contracts/interfaces/rates/ILinearKinkedRateModel.sol, contracts/rates/LinearKinkedRateModel.sol, package.json, test/foundry/RateParamsStore.t.sol
-update linear kinked rate model to use stored variables from GammaPoolFactory
-update foundry tests for linear kinked rate model
=> Feat: update linear kinked rate model

contracts/rates/LinearKinkedRateModel.sol, contracts/strategies/base/BaseStrategy.sol, package.json, test/rates/LinearKinkedRateModel.test.ts
-add function to get max yield leverage in BaseStrategy
-update linear kinked rate model to get variables from rateParamsStore
-update unit tests from linear kinked rate model
=> feat: Max CFMM Yield Leverage Function

contracts/base/PoolViewer.sol, contracts/interfaces/IGammaPool.sol, package.json
-remove maxCFMMFeeLeverage and spread params from IGammaPool
=> Feat: Remove maxCFMMFeeLeverage and spread params from IGammaPool

contracts/strategies/ShortStrategy.sol, contracts/strategies/base/BaseExternalStrategy.sol, contracts/strategies/base/BaseStrategy.sol, contracts/strategies/lending/RepayStrategy.sol, contracts/strategies/liquidation/SingleLiquidationStrategy.sol, contracts/test/strategies/base/TestBaseShortStrategy.sol, contracts/test/strategies/base/TestBaseStrategy.sol, contracts/test/strategies/base/TestBorrowStrategy.sol, contracts/test/strategies/base/TestLiquidationStrategy.sol, contracts/test/strategies/base/TestLongStrategy.sol, contracts/test/strategies/base/TestRebalanceStrategy.sol, contracts/test/strategies/base/TestRepayStrategy.sol, contracts/test/strategies/external/TestExternalBaseRebalanceStrategy.sol, package.json
-add internal function to get LP reserves from CFMM.
=> Feat: Add function to get LP reserves

contracts/libraries/LibStorage.sol, contracts/strategies/ShortStrategy.sol, contracts/strategies/base/BaseBorrowStrategy.sol, contracts/strategies/base/BaseExternalStrategy.sol, contracts/strategies/base/BaseStrategy.sol, contracts/strategies/lending/BorrowStrategy.sol, contracts/strategies/lending/RepayStrategy.sol, package.json, test/GammaPool.test.ts, test/GammaPoolFactory.test.ts, test/foundry/ExternalRebalanceStrategy.t.sol, test/strategies/LongStrategy.test.ts, test/strategies/external/ExternalLiquidationStrategy.test.ts
-cap utilization rate at 98%
-clean up outdated comments
-set default origination fee at 2bps
=> Feat: cap utilization rate

contracts/strategies/base/BaseBorrowStrategy.sol, contracts/strategies/base/BaseStrategy.sol, contracts/strategies/lending/BorrowStrategy.sol, package.json
-move checkExpectedUtilRate to _borrowLiquidity() from openLoan() and remove origination fees
=> Feat: upd check expectedutil rate

contracts/strategies/base/BaseLongStrategy.sol, contracts/strategies/lending/RepayStrategy.sol, contracts/strategies/liquidation/SingleLiquidationStrategy.sol, contracts/test/strategies/base/TestBorrowStrategy.sol, contracts/test/strategies/base/TestLiquidationStrategy.sol, contracts/test/strategies/base/TestLongStrategy.sol, contracts/test/strategies/base/TestRebalanceStrategy.sol, contracts/test/strategies/base/TestRepayStrategy.sol, contracts/test/strategies/external/TestExternalBaseStrategy.sol, contracts/test/strategies/external/TestExternalLiquidationStrategy.sol, contracts/test/strategies/external/TestExternalRebalanceStrategy.sol, package.json
-add isLiquidation parameter to calcTokensToRepay function
=> Feat: Update calcTokensToRepay function

contracts/libraries/LibStorage.sol, contracts/strategies/base/BaseLiquidationStrategy.sol, contracts/strategies/liquidation/BatchLiquidationStrategy.sol, contracts/strategies/liquidation/ExternalLiquidationStrategy.sol, contracts/strategies/liquidation/SingleLiquidationStrategy.sol, contracts/test/strategies/base/TestLiquidationStrategy.sol, contracts/test/strategies/external/TestExternalLiquidationStrategy.sol, package.json, test/GammaPool.test.ts, test/GammaPoolFactory.test.ts
-update minUtilRate default parameters
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207362881589234
=> Feat: upd minutilrate default params

contracts/strategies/base/BaseLiquidationStrategy.sol, contracts/strategies/liquidation/BatchLiquidationStrategy.sol, contracts/strategies/liquidation/ExternalLiquidationStrategy.sol, contracts/strategies/liquidation/SingleLiquidationStrategy.sol, contracts/test/strategies/base/TestLiquidationStrategy.sol, contracts/test/strategies/external/TestExternalLiquidationStrategy.sol, package.json
-change checkLiquidation to beforeLiquidation modifier to make more generic
=> Feat: checkLiquidation to beforeLiquidation modifier

contracts/base/PoolViewer.sol, contracts/interfaces/ITokenMetaData.sol, package.json, test/foundry/TokenMetaData.t.sol
-create ITokenMetaData interface and implement it in PoolViewer to get the name, symbol, and decimals per token
-add foundry tests for ITokenMetaData interface functions
=> Feat: add get name,symbol,decimals per token functions to PoolViewer

contracts/base/PoolViewer.sol, contracts/interfaces/IPoolViewer.sol, package.json
-create getLatestPoolDataWithMetaData() function in PoolViewer to return symbols and names of the tokens in a pool instead of returning them in getLatestPoolData()
=> Feat: create PoolViewer.getLatestPoolDataWithMetaData() function

contracts/base/GammaPool.sol, contracts/base/GammaPoolERC4626.sol, package.json, test/strategies/ShortStrategy.test.ts
-shrink size of GammaPool refering storage fields directly in skim and clearTooken functions
-fix ShortStrategy code formating bug
=> Feat: optimize gammapool size 20240212
